#!/usr/bin/env sh
set -eu

source="$1"

grep -q 'CVPixelBufferGetWidth' "$source"
grep -q 'VTCompressionSessionPrepareToEncodeFrames' "$source"
grep -q 'kVTInvalidSessionErr' "$source"
grep -q 'resumeAfterForeground' "$source"
grep -q 'AVCaptureSessionRuntimeError' "$source"
grep -q 'AVCaptureSessionDidStopRunning' "$source"
grep -q 'mediaServicesWereReset' "$source"
grep -q 'SENSOR %.1f' "$source"
grep -q 'HEVC %.1f' "$source"
grep -q 'USB %.1f fps' "$source"
grep -q 'didDrop sampleBuffer' "$source"
grep -q 'alwaysDiscardsLateVideoFrames = true' "$source"
grep -q 'session.sessionPreset = .inputPriority' "$source"
grep -q 'refreshActiveFormatTelemetry(device)' "$source"
grep -q 'private let sessionQueue' "$source"
grep -q 'private func apply4K60Format' "$source"
grep -q 'private func recoverSession' "$source"
grep -q 'private func scheduleRecovery' "$source"
grep -q 'private func scheduleRecoveryOnSessionQueue' "$source"
grep -q 'recoveryScheduled' "$source"
grep -q 'recoveryAttempt' "$source"
grep -q 'appIsActive' "$source"
grep -q 'handleSessionStopped' "$source"
grep -q 'sender.restartListening' "$source"
grep -q 'Encoder recovery' "$source"
grep -q 'HEVC encoder setup recovery' "$source"
grep -q 'kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange' "$source"
grep -q 'setIdleTimerDisabled(true)' "$source"
grep -q 'setIdleTimerDisabled(false)' "$source"
grep -q 'isIdleTimerDisabled' "$source"
grep -q 'thermalStateDidChangeNotification' "$source"
grep -q 'systemPressureState' "$source"
grep -q 'thermalTelemetry' "$source"
grep -q 'pressureTelemetry' "$source"
